[features]
resolution = true
skip-lint = false

[programs.localnet]
chakra_mainframe = "HHTujmzPcqDXUJMTWjcho2EvjD4cPyRHpCTcistPrVZ9"

[programs.devnet]
chakra_mainframe = "HHTujmzPcqDXUJMTWjcho2EvjD4cPyRHpCTcistPrVZ9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/chakra-mainframe.ts"

[toolchain]
anchor_version = "0.32.1"
